//! Build script for re-official plugin auto-registration.
//!
//! Reads the Cargo.toml dependencies to find `re-plugin-*` crates, then
//! reads each plugin's `manifest.yaml` to determine which contribution
//! functions it exports. Generates `official_plugin_bundles()`.
#![allow(missing_docs, clippy::panic)]

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    let cargo_toml =
        fs::read_to_string("Cargo.toml").unwrap_or_else(|e| panic!("cannot read Cargo.toml: {e}"));
    let cargo: toml::Table = cargo_toml
        .parse()
        .unwrap_or_else(|e| panic!("invalid Cargo.toml: {e}"));

    let deps = cargo
        .get("dependencies")
        .and_then(|v| v.as_table())
        .unwrap_or_else(|| panic!("missing [dependencies] in Cargo.toml"));

    let mut plugins: BTreeMap<String, PluginInfo> = BTreeMap::new();

    for (dep_name, dep_value) in deps {
        if !dep_name.starts_with("re-plugin-") {
            continue;
        }

        let path = dep_value
            .as_table()
            .and_then(|t| t.get("path"))
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("dependency '{dep_name}' must have a path"));

        let manifest_path = Path::new(path).join("manifest.yaml");
        println!("cargo:rerun-if-changed={}", manifest_path.display());

        let manifest = fs::read_to_string(&manifest_path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", manifest_path.display()));

        let rust_mod = dep_name.replace('-', "_");
        let info = parse_manifest(&manifest, &rust_mod);
        plugins.insert(dep_name.clone(), info);
    }

    let code = generate_registration(&plugins);
    let out_dir = re_build_utils::out_dir();
    let out_path = out_dir.join("plugin_registry.rs");
    fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", out_path.display()));
}

struct PluginInfo {
    rust_mod: String,
    has_templates: bool,
    has_prompts: bool,
    has_agents: bool,
    has_checks: bool,
    has_providers: bool,
    has_policies: bool,
    has_mcp_servers: bool,
    has_runtime: bool,
}

fn parse_manifest(manifest: &str, rust_mod: &str) -> PluginInfo {
    PluginInfo {
        rust_mod: rust_mod.to_owned(),
        has_templates: manifest.contains("\ntemplates:"),
        has_prompts: manifest.contains("\nprompts:"),
        has_agents: manifest.contains("\nagents:"),
        has_checks: manifest.contains("\nchecks:"),
        has_providers: manifest.contains("\nproviders:")
            || manifest.contains("data_source")
            || manifest.contains("context_provider")
            || manifest.contains("forge_provider")
            || manifest.contains("remote_control"),
        has_policies: manifest.contains("\npolicies:"),
        has_mcp_servers: manifest.contains("mcp_contribution"),
        has_runtime: manifest.contains("\nruntime: true") || manifest.contains("\nruntime:true"),
    }
}

fn generate_registration(plugins: &BTreeMap<String, PluginInfo>) -> String {
    let mut code = String::from(
        "// AUTO-GENERATED by build.rs from plugin manifest.yaml files — do not edit.\n\n\
         fn official_plugin_bundles() -> Vec<OfficialPluginBundle> {\n\
         \x20   vec![\n",
    );

    for info in plugins.values() {
        code.push_str(&generate_bundle_entry(info));
    }

    code.push_str("    ]\n}\n\n");
    code.push_str(&generate_runtime_lookup(plugins));
    code
}

/// Generates a single `official_plugin_bundle(...)` entry for a plugin.
fn generate_bundle_entry(info: &PluginInfo) -> String {
    let m = &info.rust_mod;

    let field_or_empty = |has: bool, method: &str| -> String {
        if has {
            format!("{m}::{method}()")
        } else {
            "&[]".to_owned()
        }
    };

    let templates = field_or_empty(info.has_templates, "templates");
    let prompts = field_or_empty(info.has_prompts, "prompts");
    let agents = field_or_empty(info.has_agents, "agents");
    let checks = field_or_empty(info.has_checks, "checks");
    let providers = field_or_empty(info.has_providers, "providers");
    let policies = field_or_empty(info.has_policies, "policies");
    let mcp_servers = field_or_empty(info.has_mcp_servers, "mcp_servers");

    format!(
        "        official_plugin_bundle(\n\
         \x20           {m}::descriptor(),\n\
         \x20           {templates},\n\
         \x20           {prompts},\n\
         \x20           {agents},\n\
         \x20           {checks},\n\
         \x20           {providers},\n\
         \x20           {policies},\n\
         \x20           {mcp_servers},\n\
         \x20       ),\n",
    )
}

/// Generates the `official_plugin_runtime()` match function.
fn generate_runtime_lookup(plugins: &BTreeMap<String, PluginInfo>) -> String {
    let mut code = String::from(
        "/// Returns a boxed `PluginRuntime` for one official plugin, if it provides one.\n\
         #[must_use]\n\
         pub fn official_plugin_runtime(plugin_id: &str) -> Option<Box<dyn re_plugin::PluginRuntime>> {\n\
         \x20   match plugin_id {\n",
    );

    for info in plugins.values() {
        if info.has_runtime {
            let m = &info.rust_mod;
            code.push_str(&format!(
                "        {m}::PLUGIN_ID => Some(Box::new({m}::runtime())),\n",
            ));
        }
    }

    code.push_str("        _ => None,\n    }\n}\n");
    code
}
