//! Shared build-script utilities for Ralph Engine crates.
//!
//! This crate provides helpers for `build.rs` scripts to generate
//! locale modules from TOML files. It is a build-dependency only
//! and never ships in the final binary.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

/// One parsed locale file with its identifier and key-value pairs.
#[derive(Debug)]
pub struct ParsedLocale {
    /// Locale identifier derived from filename (e.g., "en", "pt-br").
    pub id: String,
    /// Rust-safe module name (e.g., "en", "pt_br").
    pub module_name: String,
    /// Flat key-value pairs from the TOML file.
    pub entries: BTreeMap<String, String>,
}

/// Reads all `*.toml` files from a `locales/` directory and returns
/// parsed locale data sorted by identifier.
///
/// # Panics
///
/// Panics with a descriptive message if:
/// - The locales directory does not exist
/// - A TOML file cannot be read or parsed
/// - Locale files have different key sets (completeness check)
pub fn read_locale_dir(locales_dir: &Path) -> Vec<ParsedLocale> {
    let mut locales = Vec::new();

    let entries = fs::read_dir(locales_dir).unwrap_or_else(|e| {
        panic!(
            "re-build-utils: cannot read locales directory {}: {e}",
            locales_dir.display()
        );
    });

    for entry in entries {
        let entry = entry.unwrap_or_else(|e| {
            panic!("re-build-utils: cannot read directory entry: {e}");
        });
        let path = entry.path();

        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }

        let locale = parse_locale_file(&path);
        locales.push(locale);
    }

    locales.sort_by(|a, b| a.id.cmp(&b.id));
    validate_locale_completeness(&locales);

    locales
}

/// Returns `cargo:rerun-if-changed` directives for a locales directory.
pub fn rerun_if_locales_changed(locales_dir: &Path) {
    println!("cargo:rerun-if-changed={}", locales_dir.display());
    if let Ok(entries) = fs::read_dir(locales_dir) {
        for entry in entries.flatten() {
            println!("cargo:rerun-if-changed={}", entry.path().display());
        }
    }
}

/// Generates a Rust source file with `const LOCALE` definitions for a
/// flat catalog struct (all `&'static str` fields, no function pointers).
///
/// The generated code defines one `mod generated_{locale}` per locale,
/// each containing a `pub(super) const LOCALE: {struct_name}` instance.
pub fn generate_flat_locale_modules(struct_name: &str, locales: &[ParsedLocale]) -> String {
    let mut output =
        String::from("// AUTO-GENERATED by build.rs from locales/*.toml — do not edit.\n\n");

    for locale in locales {
        output.push_str(&format!("mod generated_{} {{\n", locale.module_name));
        output.push_str(&format!(
            "    pub(super) const LOCALE: super::{struct_name} = super::{struct_name} {{\n"
        ));

        for (key, value) in &locale.entries {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
            output.push_str(&format!("        {key}: \"{escaped}\",\n"));
        }

        output.push_str("    };\n");
        output.push_str("}\n\n");
    }

    output
}

/// Generates a Rust source file with `const LOCALE` definitions that
/// include function pointer fields referencing hand-coded `fn_{locale}`
/// modules.
///
/// `fn_fields` is a list of field names that are `fn(...)` pointers.
/// These are emitted as `super::fn_{locale}::{field_name}` references.
pub fn generate_locale_modules_with_fns(
    struct_name: &str,
    locales: &[ParsedLocale],
    fn_fields: &[&str],
) -> String {
    let mut output =
        String::from("// AUTO-GENERATED by build.rs from locales/*.toml — do not edit.\n\n");

    for locale in locales {
        output.push_str(&format!("mod generated_{} {{\n", locale.module_name));
        output.push_str(&format!(
            "    pub(super) const LOCALE: super::{struct_name} = super::{struct_name} {{\n"
        ));

        for (key, value) in &locale.entries {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
            output.push_str(&format!("        {key}: \"{escaped}\",\n"));
        }

        for fn_field in fn_fields {
            output.push_str(&format!(
                "        {fn_field}: super::fn_{}::{fn_field},\n",
                locale.module_name
            ));
        }

        output.push_str("    };\n");
        output.push_str("}\n\n");
    }

    output
}

/// Generates the `locale_catalog()` dispatch function body that matches
/// `SupportedLocale` variants to generated modules.
pub fn generate_dispatch_function(struct_name: &str, locales: &[ParsedLocale]) -> String {
    let mut output = String::new();
    output.push_str(&format!(
        "fn locale_catalog(locale: &str) -> &'static {struct_name} {{\n"
    ));
    output.push_str("    match re_config::resolve_supported_locale_or_default(locale) {\n");

    for locale in locales {
        let variant = locale_id_to_variant(&locale.id);
        output.push_str(&format!(
            "        re_config::SupportedLocale::{variant} => &generated_{}::LOCALE,\n",
            locale.module_name
        ));
    }

    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

/// Resolves the output directory for generated code.
pub fn out_dir() -> PathBuf {
    PathBuf::from(std::env::var("OUT_DIR").unwrap_or_else(|_| {
        panic!("re-build-utils: OUT_DIR not set — this must be called from build.rs");
    }))
}

// --- internal helpers ---

fn parse_locale_file(path: &Path) -> ParsedLocale {
    let filename = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_else(|| {
            panic!(
                "re-build-utils: cannot extract filename from {}",
                path.display()
            );
        });

    let id = filename.to_owned();
    let module_name = filename.replace('-', "_");

    let contents = fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("re-build-utils: cannot read {}: {e}", path.display());
    });

    let table: toml::Table = contents.parse().unwrap_or_else(|e| {
        panic!("re-build-utils: invalid TOML in {}: {e}", path.display());
    });

    let mut entries = BTreeMap::new();
    collect_flat_entries(&table, &mut entries, path);

    ParsedLocale {
        id,
        module_name,
        entries,
    }
}

fn collect_flat_entries(table: &toml::Table, out: &mut BTreeMap<String, String>, path: &Path) {
    for (key, value) in table {
        match value {
            toml::Value::String(s) => {
                out.insert(key.clone(), s.clone());
            }
            toml::Value::Table(sub) => {
                // Nested tables are flattened for plugin TOML format
                // but we store them under a section prefix for later use
                for (sub_key, sub_value) in sub {
                    if let toml::Value::String(s) = sub_value {
                        out.insert(format!("{key}.{sub_key}"), s.clone());
                    } else {
                        panic!(
                            "re-build-utils: unsupported nested value in {} at {key}.{sub_key}",
                            path.display()
                        );
                    }
                }
            }
            _ => {
                panic!(
                    "re-build-utils: unsupported TOML value type in {} at key '{key}'",
                    path.display()
                );
            }
        }
    }
}

fn validate_locale_completeness(locales: &[ParsedLocale]) {
    if locales.len() < 2 {
        return;
    }

    let reference = &locales[0];
    let ref_keys: Vec<&String> = reference.entries.keys().collect();

    for locale in &locales[1..] {
        let locale_keys: Vec<&String> = locale.entries.keys().collect();

        // Check for missing keys
        for key in &ref_keys {
            if !locale.entries.contains_key(*key) {
                panic!(
                    "re-build-utils: locale '{}' is missing key '{}' (present in '{}')",
                    locale.id, key, reference.id
                );
            }
        }

        // Check for extra keys
        for key in &locale_keys {
            if !reference.entries.contains_key(*key) {
                panic!(
                    "re-build-utils: locale '{}' has extra key '{}' (not present in '{}')",
                    locale.id, key, reference.id
                );
            }
        }
    }
}

fn locale_id_to_variant(id: &str) -> String {
    // "en" → "En", "pt-br" → "PtBr"
    id.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    format!("{upper}{}", chars.as_str())
                }
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn locale_id_to_variant_converts_correctly() {
        assert_eq!(locale_id_to_variant("en"), "En");
        assert_eq!(locale_id_to_variant("pt-br"), "PtBr");
        assert_eq!(locale_id_to_variant("es"), "Es");
        assert_eq!(locale_id_to_variant("zh-cn"), "ZhCn");
    }

    #[test]
    fn parse_locale_file_reads_flat_toml() {
        let dir = std::env::temp_dir().join("re-build-utils-test-flat");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).ok();
        fs::write(
            dir.join("en.toml"),
            "greeting = \"Hello\"\nfarewell = \"Goodbye\"\n",
        )
        .ok();

        let locale = parse_locale_file(&dir.join("en.toml"));

        assert_eq!(locale.id, "en");
        assert_eq!(locale.module_name, "en");
        assert_eq!(locale.entries["greeting"], "Hello");
        assert_eq!(locale.entries["farewell"], "Goodbye");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn parse_locale_file_reads_nested_toml() {
        let dir = std::env::temp_dir().join("re-build-utils-test-nested");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).ok();
        fs::write(
            dir.join("en.toml"),
            "[plugin]\nname = \"Test\"\nsummary = \"A test plugin.\"\n",
        )
        .ok();

        let locale = parse_locale_file(&dir.join("en.toml"));

        assert_eq!(locale.entries["plugin.name"], "Test");
        assert_eq!(locale.entries["plugin.summary"], "A test plugin.");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_flat_locale_modules_produces_valid_structure() {
        let locales = vec![
            ParsedLocale {
                id: "en".to_owned(),
                module_name: "en".to_owned(),
                entries: BTreeMap::from([("greeting".to_owned(), "Hello".to_owned())]),
            },
            ParsedLocale {
                id: "pt-br".to_owned(),
                module_name: "pt_br".to_owned(),
                entries: BTreeMap::from([("greeting".to_owned(), "Olá".to_owned())]),
            },
        ];

        let output = generate_flat_locale_modules("TestCatalog", &locales);

        assert!(output.contains("mod generated_en"));
        assert!(output.contains("mod generated_pt_br"));
        assert!(output.contains("greeting: \"Hello\""));
        assert!(output.contains("greeting: \"Olá\""));
        assert!(output.contains("super::TestCatalog"));
    }

    #[test]
    fn generate_dispatch_function_produces_match() {
        let locales = vec![
            ParsedLocale {
                id: "en".to_owned(),
                module_name: "en".to_owned(),
                entries: BTreeMap::new(),
            },
            ParsedLocale {
                id: "pt-br".to_owned(),
                module_name: "pt_br".to_owned(),
                entries: BTreeMap::new(),
            },
        ];

        let output = generate_dispatch_function("TestCatalog", &locales);

        assert!(output.contains("SupportedLocale::En => &generated_en::LOCALE"));
        assert!(output.contains("SupportedLocale::PtBr => &generated_pt_br::LOCALE"));
    }
}
