name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594
        with:
          egress-policy: audit
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
